language: node_js

node_js:
  - "stable"

install:
  - npm install

services:
  - postgresql
addons:
  postgresql: "12"
  apt:
    packages:
      - postgresql-12
      - postgresql-client-12

env:
  global:
    - PGPORT=5433
    - DB_TEST=ireporter_test
    - DB_USER=ireporter
    - DB_PASSWORD=ireporterPassword

before_script:
  - psql --command="CREATE USER ${DB_USER};"
  - psql --command="CREATE DATABASE ${DB_NAME} WITH OWNER = ${DB_USER};"

cache:
  directories:
    - node_modules

script:
  - npm test

after_success:
  - npm run coverage

notifications:
  email: false
