language: node_js

node_js:
  - "stable"

install:
  - npm install

services:
  - postgresql
addons:
  postgresql: "9.6"

env:
  - NODE_ENV="test"

before_script:
  - psql -c 'create database ireporter_test_db;' -U postgres

cache:
  directories:
    - node_modules

script:
  - npm test

after_success:
  - npm run coverage

notifications:
  email: false
